version: '3'
services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:20-bookworm
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:postgres
    command: sleep infinity
  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
volumes:
  postgres-data:
